version: '3.8'

services:
  postgres:
    image: "postgres:14.1-alpine"
    hostname: postgresql
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5428:5432"
    env_file:
      - .env

  redis:
    image: "redis:7.2.4-alpine"
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data


  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.11
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

volumes:
  postgres-data:
  cache:
